# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('company', models.CharField(max_length=20, verbose_name='公司')),
                ('pay_a', models.IntegerField(verbose_name='最低薪资')),
                ('pay_b', models.IntegerField(verbose_name='最高薪资')),
                ('address', models.CharField(max_length=20, verbose_name='公司地址')),
                ('job_term', models.TextField(verbose_name='入职要求')),
                ('job_des', models.TextField(verbose_name='描述信息')),
            ],
        ),
    ]
